<?php

/**
 * @file
 * Contains training.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function training_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the training module.
    case 'help.page.training':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Training Module') . '</p>';
      return $output;

    default:
  }
}
